# Generated by Django 3.2.11 on 2022-01-10 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_auto_20220110_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tool1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
