# Generated by Django 3.2.11 on 2022-01-10 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_project_tool1'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link1',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='link2',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
