# Generated by Django 3.2.11 on 2022-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_auto_20220110_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link1',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='link2',
            field=models.URLField(max_length=500),
        ),
    ]
